# This file was generated by GoReleaser. DO NOT EDIT.
cask "t9s" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "c5569a1b3a113e632137188cfb02027d271842d2c939e641d22f2259814d2517"
      url "https://github.com/florianspk/t9s/releases/download/v#{version}/t9s_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e14ad826fcb965e5c632a6f32eb93c0cab680dd055075e6ab12582ba873a4b27"
      url "https://github.com/florianspk/t9s/releases/download/v#{version}/t9s_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "45852b34c6b00c4dfdd1a1b9cb8a2f98ef3222f026b8e92f98e3fd628a3b38ff"
      url "https://github.com/florianspk/t9s/releases/download/v#{version}/t9s_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "544d2deac104ebf2ec0fb2a77e24744601f47e62ca9d71d7bf4cbca253594d5b"
      url "https://github.com/florianspk/t9s/releases/download/v#{version}/t9s_#{version}_linux_amd64.tar.gz"
    end
  end

  name "t9s"
  desc "k9s-inspired TUI for managing Talos Linux clusters via talosctl"
  homepage "https://github.com/florianspk/t9s"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "t9s"

  # No zap stanza required
end
