# This file was generated by GoReleaser. DO NOT EDIT.
cask "t9s" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "029c45797eabe8245bffaee6324345f3481a7a2e99bb6653ed33ed0a17a0aeaf"
      url "https://github.com/florianspk/t9s/releases/download/v#{version}/t9s_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/florianspk/t9s/"
    end
    on_arm do
      sha256 "14310de2af7b08170f07cdb28d2cc989a1186e7f6a1d12b4b4003bc6c14921c7"
      url "https://github.com/florianspk/t9s/releases/download/v#{version}/t9s_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/florianspk/t9s/"
    end
  end

  on_linux do
    on_intel do
      sha256 "59dee4a1610329cb22aabc747ab79efc1c50037c7765b482614531b4848bcadb"
      url "https://github.com/florianspk/t9s/releases/download/v#{version}/t9s_#{version}_linux_amd64.tar.gz",
        verified: "github.com/florianspk/t9s/"
    end
    on_arm do
      sha256 "080a53ce8ddfcd582616e05832bbfd91c4393cecd98161f3b9e3cc287be024c7"
      url "https://github.com/florianspk/t9s/releases/download/v#{version}/t9s_#{version}_linux_arm64.tar.gz",
        verified: "github.com/florianspk/t9s/"
    end
  end

  name "t9s"
  desc "k9s-inspired TUI for managing Talos Linux clusters via talosctl"
  homepage "https://github.com/florianspk/t9s"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "t9s"

  # No zap stanza required

end
