# This file was generated by GoReleaser. DO NOT EDIT.
cask "t9s" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "94e860c0957b16b3cfeeb6b74090abf427bc041e4d1e326aed9320caf3ebc007"
      url "https://github.com/florianspk/t9s/releases/download/v#{version}/t9s_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/florianspk/t9s/"
    end
    on_arm do
      sha256 "15cbd1f2a7f7c9e48e2109a61f39c718b0820581134a5687ece401371264cab8"
      url "https://github.com/florianspk/t9s/releases/download/v#{version}/t9s_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/florianspk/t9s/"
    end
  end

  on_linux do
    on_intel do
      sha256 "a028091e8153a03600ee608b528774bcb834d7dc22bb4786746821e976239767"
      url "https://github.com/florianspk/t9s/releases/download/v#{version}/t9s_#{version}_linux_amd64.tar.gz",
        verified: "github.com/florianspk/t9s/"
    end
    on_arm do
      sha256 "bc1d2b4c8dd12645a6dc5bc3b58c54eca520dc0e738be70184e0f0d33ea53ea0"
      url "https://github.com/florianspk/t9s/releases/download/v#{version}/t9s_#{version}_linux_arm64.tar.gz",
        verified: "github.com/florianspk/t9s/"
    end
  end

  name "t9s"
  desc "k9s-inspired TUI for managing Talos Linux clusters via talosctl"
  homepage "https://github.com/florianspk/t9s"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "t9s"

  # No zap stanza required

end
