# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class T9s < Formula
  desc "k9s-inspired TUI for managing Talos Linux clusters via talosctl"
  homepage "https://github.com/florianspk/t9s"
  version "0.1.0"
  license "Non-Commercial Source-Available"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/florianspk/t9s/releases/download/v0.1.0/t9s_0.1.0_darwin_amd64.tar.gz"
      sha256 "123d49abfe4e54f829477bdc5aeebfb76d416b43be896dc7ba1a38f06d9a5f63"

      define_method(:install) do
        bin.install "t9s"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/florianspk/t9s/releases/download/v0.1.0/t9s_0.1.0_darwin_arm64.tar.gz"
      sha256 "55d6e0287f9eee448ced960895b34c987032e50f2b513baa483d7133c5b9b94c"

      define_method(:install) do
        bin.install "t9s"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/florianspk/t9s/releases/download/v0.1.0/t9s_0.1.0_linux_amd64.tar.gz"
      sha256 "91e44939afbea089991d4dff0ede60459f86ac7da8ac900d2bafbeb077114e56"
      define_method(:install) do
        bin.install "t9s"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/florianspk/t9s/releases/download/v0.1.0/t9s_0.1.0_linux_arm64.tar.gz"
      sha256 "bbe8a54221123b08fb0a17679644017e3144c5a27c17104c599754789da0b023"
      define_method(:install) do
        bin.install "t9s"
      end
    end
  end

  test do
    system "#{bin}/t9s --version"
  end
end
